# Generated by Django 4.0.6 on 2022-07-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='slug',
            field=models.SlugField(blank=True, max_length=42, unique=True),
        ),
    ]
