run-dev:
	python manage.py runserver --settings=core.settings.local

makemigrate-dev:
	python manage.py makemigrations --settings=core.settings.local

migrate-dev:
	python manage.py migrate --settings=core.settings.local


run:
	python manage.py runserver --settings=core.settings.prod

makemigrate:
	python manage.py makemigrations --settings=core.settings.prod

migrate:
	python manage.py migrate --settings=core.settings.prod