# Generated by Django 4.0.6 on 2022-07-18 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_galleryalbumimage_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryalbumimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryalbumimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='galleryalbumimage',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
