# Generated by Django 4.0.6 on 2022-07-18 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_galleryalbumimage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryalbum',
            options={'verbose_name': 'Album image', 'verbose_name_plural': 'Album images'},
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='slug',
            field=models.SlugField(blank=True, max_length=42, unique=True),
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
