# Generated by Django 4.0.6 on 2022-07-18 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_galleryalbum_options_galleryalbum_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryalbumimage',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.galleryalbum'),
            preserve_default=False,
        ),
    ]
