# Generated by Django 4.0.6 on 2022-07-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_rename_image_height_galleryalbumimage_height_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryalbum',
            options={'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
    ]
