# Generated by Django 4.0.6 on 2022-07-18 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_galleryalbum_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryalbumimage',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='gallery.galleryalbum'),
        ),
    ]
