# Generated by Django 4.0.6 on 2022-07-19 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_galleryalbumimage_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryalbum',
            old_name='visible',
            new_name='is_visible',
        ),
        migrations.RenameField(
            model_name='galleryalbumimage',
            old_name='visible',
            new_name='is_visible',
        ),
    ]
