# Generated by Django 4.0.6 on 2022-07-20 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_rename_visible_galleryalbum_is_visible_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryalbum',
            options={'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='galleryalbumimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
