# Generated by Django 4.0.6 on 2022-07-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_alter_galleryalbumimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryalbumimage',
            name='origin_height',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='galleryalbumimage',
            name='origin_width',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='galleryalbumimage',
            name='image',
            field=models.ImageField(height_field='height', upload_to='gallery_album_images', width_field='width'),
        ),
    ]
