# Generated by Django 4.0.6 on 2022-07-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_galleryalbumimage_origin_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryalbumimage',
            name='image',
            field=models.ImageField(upload_to='gallery_album_images'),
        ),
    ]
