# Generated by Django 4.0.6 on 2022-07-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('inn', models.IntegerField(verbose_name='ИНН')),
                ('kpp', models.IntegerField(verbose_name='КПП')),
                ('ogrn', models.IntegerField(verbose_name='ОГРН')),
                ('okpo', models.IntegerField(verbose_name='ОКПО')),
                ('payment_account', models.IntegerField(verbose_name='Расчетный счет')),
                ('bank', models.TextField(verbose_name='Банк')),
                ('bic', models.IntegerField(verbose_name='БИК')),
                ('correspondent_account', models.IntegerField(verbose_name='Корр. счет')),
                ('legal_address', models.TextField(verbose_name='Юридический адрес')),
                ('telephone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('abbot', models.CharField(max_length=100, verbose_name='Настоятель')),
                ('slug', models.SlugField(blank=True, max_length=42, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимость')),
            ],
            options={
                'verbose_name': 'Пожертвование',
                'verbose_name_plural': 'Пожертвования',
            },
        ),
    ]
