# Generated by Django 4.0.6 on 2022-07-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='correspondent_account',
            field=models.BigIntegerField(verbose_name='Корр. счет'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='ogrn',
            field=models.BigIntegerField(verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_account',
            field=models.BigIntegerField(verbose_name='Расчетный счет'),
        ),
    ]
