# Generated by Django 4.0.6 on 2022-07-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_alter_donation_correspondent_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='bic',
            field=models.BigIntegerField(verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='inn',
            field=models.BigIntegerField(verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='kpp',
            field=models.BigIntegerField(verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='okpo',
            field=models.BigIntegerField(verbose_name='ОКПО'),
        ),
    ]
