# Generated by Django 4.0.6 on 2022-07-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_alter_donation_bic_alter_donation_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='bic',
            field=models.CharField(max_length=20, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='correspondent_account',
            field=models.CharField(max_length=20, verbose_name='Корр. счет'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='inn',
            field=models.CharField(max_length=20, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='kpp',
            field=models.CharField(max_length=20, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='ogrn',
            field=models.CharField(max_length=20, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='okpo',
            field=models.CharField(max_length=20, verbose_name='ОКПО'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_account',
            field=models.CharField(max_length=20, verbose_name='Расчетный счет'),
        ),
    ]
