# Generated by Django 4.0.6 on 2022-07-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cleric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('data', models.JSONField()),
                ('photo', models.ImageField(upload_to='')),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Клирик',
                'verbose_name_plural': 'Клирики',
            },
        ),
    ]
