# Generated by Django 4.0.6 on 2022-07-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clergy', '0002_alter_cleric_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleric',
            name='photo',
            field=models.ImageField(upload_to='cleric_photo'),
        ),
    ]
