# Generated by Django 4.0.6 on 2022-07-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clergy', '0003_alter_cleric_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleric',
            name='photo',
            field=models.ImageField(blank=True, upload_to='cleric_photo'),
        ),
    ]
