# Generated by Django 4.0.6 on 2022-07-20 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clergy', '0004_alter_cleric_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleric',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cleric',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
